package com.cnrmall.rules;
dialect  "java"
import com.ytooo.bean.OrderInfo;


rule "dispatch1"
    salience 100 // 优先级：值越大，优先级越高
    when
      $order: OrderInfo(categoryName.equals("酒") )
    then
      $order.getLogistics().add("京东");
end
rule "dispatch2"
    salience 50
    when
      $order: OrderInfo(weight < 3, (price > 0 && price < 500))
    then
        $order.getLogistics().add("圆通");
        $order.getLogistics().add("中通");
end
rule "dispatch3"
    salience 20
    when
        $order: OrderInfo(weight < 3, (price > 500 && price < 1000))
    then
        $order.getLogistics().add("顺丰");
        $order.getLogistics().add("京东");
        $order.getLogistics().add("极兔");
        $order.getLogistics().add("德邦");
end
rule "dispatch4"
    salience 0
    when
     $order: OrderInfo()
    then
        if (!$order.getLogistics().contains("京东") ) {
            $order.getLogistics().add("京东");
        }
end

